# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/Kria_Constraints.xdc

# Block Designs: bd/Kria_BD/Kria_BD.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD || ORIG_REF_NAME==Kria_BD} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_zynq_ultra_ps_e_0_0/Kria_BD_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Kria_BD_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_clk_wiz_0_1/Kria_BD_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_clk_wiz_0_1 || ORIG_REF_NAME==Kria_BD_clk_wiz_0_1} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_proc_sys_reset_0_0/Kria_BD_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_proc_sys_reset_0_0 || ORIG_REF_NAME==Kria_BD_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_proc_sys_reset_1_0/Kria_BD_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_proc_sys_reset_1_0 || ORIG_REF_NAME==Kria_BD_proc_sys_reset_1_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_intc_0_0/Kria_BD_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_intc_0_0 || ORIG_REF_NAME==Kria_BD_axi_intc_0_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_xbar_0/Kria_BD_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_xbar_0 || ORIG_REF_NAME==Kria_BD_xbar_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_tier2_xbar_0_0/Kria_BD_tier2_xbar_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_tier2_xbar_0_0 || ORIG_REF_NAME==Kria_BD_tier2_xbar_0_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_tier2_xbar_1_0/Kria_BD_tier2_xbar_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_tier2_xbar_1_0 || ORIG_REF_NAME==Kria_BD_tier2_xbar_1_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_tier2_xbar_2_0/Kria_BD_tier2_xbar_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_tier2_xbar_2_0 || ORIG_REF_NAME==Kria_BD_tier2_xbar_2_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_auto_pc_0/Kria_BD_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_auto_pc_0 || ORIG_REF_NAME==Kria_BD_auto_pc_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_ps8_0_axi_periph_0/Kria_BD_ps8_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_ps8_0_axi_periph_0 || ORIG_REF_NAME==Kria_BD_ps8_0_axi_periph_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_iic_0_0/Kria_BD_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_iic_0_0 || ORIG_REF_NAME==Kria_BD_axi_iic_0_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_0_0/Kria_BD_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_0_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_0_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_1_0/Kria_BD_axi_gpio_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_1_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_1_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_2_0/Kria_BD_axi_gpio_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_2_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_2_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_3_0/Kria_BD_axi_gpio_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_3_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_3_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_4_0/Kria_BD_axi_gpio_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_4_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_4_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_5_0/Kria_BD_axi_gpio_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_5_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_5_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_6_0/Kria_BD_axi_gpio_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_6_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_6_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_7_0/Kria_BD_axi_gpio_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_7_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_7_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_8_0/Kria_BD_axi_gpio_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_8_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_8_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_9_0/Kria_BD_axi_gpio_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_9_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_9_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_10_0/Kria_BD_axi_gpio_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_10_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_10_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_11_0/Kria_BD_axi_gpio_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_11_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_11_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_12_0/Kria_BD_axi_gpio_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_12_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_12_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_13_0/Kria_BD_axi_gpio_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_13_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_13_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_axi_gpio_14_0/Kria_BD_axi_gpio_14_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_14_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_14_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_0_0/Kria_BD_motor_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_0_0 || ORIG_REF_NAME==Kria_BD_motor_controller_0_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_10_0/Kria_BD_motor_controller_10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_10_0 || ORIG_REF_NAME==Kria_BD_motor_controller_10_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_11_0/Kria_BD_motor_controller_11_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_11_0 || ORIG_REF_NAME==Kria_BD_motor_controller_11_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_12_0/Kria_BD_motor_controller_12_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_12_0 || ORIG_REF_NAME==Kria_BD_motor_controller_12_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_13_0/Kria_BD_motor_controller_13_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_13_0 || ORIG_REF_NAME==Kria_BD_motor_controller_13_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_1_0/Kria_BD_motor_controller_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_1_0 || ORIG_REF_NAME==Kria_BD_motor_controller_1_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_2_0/Kria_BD_motor_controller_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_2_0 || ORIG_REF_NAME==Kria_BD_motor_controller_2_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_3_0/Kria_BD_motor_controller_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_3_0 || ORIG_REF_NAME==Kria_BD_motor_controller_3_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_4_0/Kria_BD_motor_controller_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_4_0 || ORIG_REF_NAME==Kria_BD_motor_controller_4_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_5_0/Kria_BD_motor_controller_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_5_0 || ORIG_REF_NAME==Kria_BD_motor_controller_5_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_6_0/Kria_BD_motor_controller_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_6_0 || ORIG_REF_NAME==Kria_BD_motor_controller_6_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_7_0/Kria_BD_motor_controller_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_7_0 || ORIG_REF_NAME==Kria_BD_motor_controller_7_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_8_0/Kria_BD_motor_controller_8_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_8_0 || ORIG_REF_NAME==Kria_BD_motor_controller_8_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_motor_controller_9_0/Kria_BD_motor_controller_9_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_motor_controller_9_0 || ORIG_REF_NAME==Kria_BD_motor_controller_9_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_watchdog_0_0/Kria_BD_watchdog_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_watchdog_0_0 || ORIG_REF_NAME==Kria_BD_watchdog_0_0} -quiet] -quiet

# IP: bd/Kria_BD/ip/Kria_BD_xlconstant_0_0/Kria_BD_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Kria_BD_xlconstant_0_0 || ORIG_REF_NAME==Kria_BD_xlconstant_0_0} -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_zynq_ultra_ps_e_0_0/Kria_BD_zynq_ultra_ps_e_0_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_zynq_ultra_ps_e_0_0/Kria_BD_zynq_ultra_ps_e_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==Kria_BD_zynq_ultra_ps_e_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_clk_wiz_0_1/Kria_BD_clk_wiz_0_1_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_clk_wiz_0_1 || ORIG_REF_NAME==Kria_BD_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_clk_wiz_0_1/Kria_BD_clk_wiz_0_1.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_clk_wiz_0_1 || ORIG_REF_NAME==Kria_BD_clk_wiz_0_1} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_clk_wiz_0_1/Kria_BD_clk_wiz_0_1_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_proc_sys_reset_0_0/Kria_BD_proc_sys_reset_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_proc_sys_reset_0_0 || ORIG_REF_NAME==Kria_BD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_proc_sys_reset_0_0/Kria_BD_proc_sys_reset_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_proc_sys_reset_0_0 || ORIG_REF_NAME==Kria_BD_proc_sys_reset_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_proc_sys_reset_1_0/Kria_BD_proc_sys_reset_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_proc_sys_reset_1_0 || ORIG_REF_NAME==Kria_BD_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_proc_sys_reset_1_0/Kria_BD_proc_sys_reset_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_proc_sys_reset_1_0 || ORIG_REF_NAME==Kria_BD_proc_sys_reset_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_intc_0_0/Kria_BD_axi_intc_0_0.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_intc_0_0 || ORIG_REF_NAME==Kria_BD_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_intc_0_0/Kria_BD_axi_intc_0_0_clocks.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_intc_0_0 || ORIG_REF_NAME==Kria_BD_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_intc_0_0/Kria_BD_axi_intc_0_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_auto_pc_0/Kria_BD_auto_pc_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_iic_0_0/Kria_BD_axi_iic_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_iic_0_0 || ORIG_REF_NAME==Kria_BD_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_iic_0_0/Kria_BD_axi_iic_0_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_0_0/Kria_BD_axi_gpio_0_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_0_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_0_0/Kria_BD_axi_gpio_0_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_0_0/Kria_BD_axi_gpio_0_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_0_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_1_0/Kria_BD_axi_gpio_1_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_1_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_1_0/Kria_BD_axi_gpio_1_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_1_0/Kria_BD_axi_gpio_1_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_1_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_2_0/Kria_BD_axi_gpio_2_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_2_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_2_0/Kria_BD_axi_gpio_2_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_2_0/Kria_BD_axi_gpio_2_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_2_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_2_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_3_0/Kria_BD_axi_gpio_3_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_3_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_3_0/Kria_BD_axi_gpio_3_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_3_0/Kria_BD_axi_gpio_3_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_3_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_3_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_4_0/Kria_BD_axi_gpio_4_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_4_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_4_0/Kria_BD_axi_gpio_4_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_4_0/Kria_BD_axi_gpio_4_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_4_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_4_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_5_0/Kria_BD_axi_gpio_5_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_5_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_5_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_5_0/Kria_BD_axi_gpio_5_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_5_0/Kria_BD_axi_gpio_5_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_5_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_5_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_6_0/Kria_BD_axi_gpio_6_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_6_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_6_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_6_0/Kria_BD_axi_gpio_6_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_6_0/Kria_BD_axi_gpio_6_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_6_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_6_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_7_0/Kria_BD_axi_gpio_7_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_7_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_7_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_7_0/Kria_BD_axi_gpio_7_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_7_0/Kria_BD_axi_gpio_7_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_7_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_7_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_8_0/Kria_BD_axi_gpio_8_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_8_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_8_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_8_0/Kria_BD_axi_gpio_8_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_8_0/Kria_BD_axi_gpio_8_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_8_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_8_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_9_0/Kria_BD_axi_gpio_9_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_9_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_9_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_9_0/Kria_BD_axi_gpio_9_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_9_0/Kria_BD_axi_gpio_9_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_9_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_9_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_10_0/Kria_BD_axi_gpio_10_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_10_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_10_0/Kria_BD_axi_gpio_10_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_10_0/Kria_BD_axi_gpio_10_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_10_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_11_0/Kria_BD_axi_gpio_11_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_11_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_11_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_11_0/Kria_BD_axi_gpio_11_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_11_0/Kria_BD_axi_gpio_11_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_11_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_11_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_12_0/Kria_BD_axi_gpio_12_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_12_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_12_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_12_0/Kria_BD_axi_gpio_12_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_12_0/Kria_BD_axi_gpio_12_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_12_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_12_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_13_0/Kria_BD_axi_gpio_13_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_13_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_13_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_13_0/Kria_BD_axi_gpio_13_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_13_0/Kria_BD_axi_gpio_13_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_13_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_13_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_14_0/Kria_BD_axi_gpio_14_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_14_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_14_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_14_0/Kria_BD_axi_gpio_14_0_ooc.xdc

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/ip/Kria_BD_axi_gpio_14_0/Kria_BD_axi_gpio_14_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==Kria_BD_axi_gpio_14_0 || ORIG_REF_NAME==Kria_BD_axi_gpio_14_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: c:/Users/simba/Desktop/Kria_KR260_PMOD/Kria_KR260_Test.gen/sources_1/bd/Kria_BD/Kria_BD_ooc.xdc
